version: 2

sources:
  - name: raw_weather_data
    database: calm-suprstate-481612-s3
    schema: raw_weather_data
    config:
      location: 'EU'  
    tables:
      - name: amsterdam_historical_weather_2
        description: "raw weather data from openweather API"
        columns:
          - name: date
            description: date of weather data
            tests:
              - not_null
              - unique 